export const accounts = [
  {
    accountNumber: "001",
    companyName: "Tech Innovators Inc.",
    contactName: "Alice Johnson",
    phoneNumber: "123-456-7890",
    email: "alice@techinnovators.com",
    accountStatus: "Open",
    creationDate: "2025-02-01",
    virtualCompany: "Example Company A",
  },
  {
    accountNumber: "002",
    companyName: "Green Energy LLC",
    contactName: "Bob Smith",
    phoneNumber: "234-567-8901",
    email: "bob@greenenergy.com",
    accountStatus: "Closed",
    creationDate: "2025-02-01",
    virtualCompany: "Example Company B",
  },
  {
    accountNumber: "003",
    companyName: "Health Plus Corp.",
    contactName: "Carol White",
    phoneNumber: "345-678-9012",
    email: "carol@healthplus.com",
    accountStatus: "Collections",
    creationDate: "2025-01-25",
    virtualCompany: "Example Company C",
  },
  {
    accountNumber: "004",
    companyName: "EduTech Solutions",
    contactName: "David Brown",
    phoneNumber: "456-789-0123",
    email: "david@edutech.com",
    accountStatus: "Suspended",
    creationDate: "2025-01-15",
    virtualCompany: "Example Company D",
  },
  {
    accountNumber: "005",
    companyName: "AutoDrive Co.",
    contactName: "Eve Davis",
    phoneNumber: "567-890-1234",
    email: "eve@autodrive.com",
    accountStatus: "Open",
    creationDate: "2025-01-15",
    virtualCompany: "Example Company E",
  },
  {
    accountNumber: "006",
    companyName: "CloudNet Technologies",
    contactName: "Frank Harris",
    phoneNumber: "678-901-2345",
    email: "frank@cloudnet.com",
    accountStatus: "Closed",
    creationDate: "2024-12-20",
    virtualCompany: "Example Company F",
  },
  {
    accountNumber: "007",
    companyName: "AgroGoods Ltd.",
    contactName: "Grace Lee",
    phoneNumber: "789-012-3456",
    email: "grace@agrogoods.com",
    accountStatus: "Collections",
    creationDate: "2024-12-15",
    virtualCompany: "Example Company G",
  },
  {
    accountNumber: "008",
    companyName: "CyberShield Security",
    contactName: "Henry Adams",
    phoneNumber: "890-123-4567",
    email: "henry@cybershield.com",
    accountStatus: "Suspended",
    creationDate: "2024-11-05",
    virtualCompany: "Example Company H",
  },
  {
    accountNumber: "009",
    companyName: "SolarTech Innovations",
    contactName: "Isabella Moore",
    phoneNumber: "901-234-5678",
    email: "isabella@solartech.com",
    accountStatus: "Open",
    creationDate: "2024-11-05",
    virtualCompany: "Example Company I",
  },
  {
    accountNumber: "010",
    companyName: "Quantum AI Solutions",
    contactName: "Jack Thompson",
    phoneNumber: "012-345-6789",
    email: "jack@quantumai.com",
    accountStatus: "Closed",
    creationDate: "2025-01-10",
    virtualCompany: "Example Company J",
  },
];
